### PR TITLE
Adds Support for JSON Serialization/Deserialization

### PR DESCRIPTION
**Pull request by phranck**
### ADDITIONS
* mixin MetadataKeys for string constants with field names of the `Metadata` object
* instance method `toJson()` and static method `fromJson(..)`
* getter `Metadata.hasAllMetadata`

### CHANGES
* rewrite from "old" `abstract class` API to the modern `mixin` API

### FIXES
* Fixes a Bug in the `url` getter of `TwitterCardParser`, `JsonLdParser` and `HtmlMetaParser`
* Fixes a bug in `image` getter of `JsonLdParser`

### CODE REVIEW

**Comment by jg-l** [comment]
Thanks for this, once again. I am considering reworking the strategy for the JsonLD Parser. It will cause too much runtime errors as the implementation of the schema isn't as rigid and universal across the web. This is why the image-getter for the JsonLDParser is quite buggy.

What do you think?

(Will checkout this PR in a few, Covid Madness at my work isn't giving me much time nowadays)

**Comment by phranck** [comment]
I totally agree. Good idea. Making this plugin as robust as possible will bring us lots benefits.

**Comment by phranck** [comment]
@jg-l Your commit message for the merge says version `3.0.1`. I guess it's typo and you meant `0.3.1`, though. 🙃

**Comment by jg-l** [comment]
Oops 😂

Yes it's still 0.3.1. On pub.dev as well!

**Pull request merged**
